name: ğŸš€ Auto PR to Develop

on:
  workflow_call:

jobs:
  create-pr-to-develop:
    name: ğŸ”€ Create PR to Develop
    runs-on: ubuntu-latest
    # NÃ£o Ã© necessÃ¡rio declarar secrets aqui
    steps:
      - name: ğŸ›ï¸ Checkout code
        uses: actions/checkout@v4

      - name: ğŸ”‘ Print token presence
        run: |
          if [ -z "${{ secrets.TOKEN }}" ]; then
            echo "TOKEN is NOT available in this repository."
            exit 1
          else
            echo "TOKEN is available in this repository."
          fi

      - name: ğŸ”€ Create Pull Request to develop
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.TOKEN }}
          base: develop
          branch: ${{ github.ref_name }}
          title: 'Auto PR: ${{ github.ref_name }} â†’ develop'
          body: |
            PR automÃ¡tico criado pelo workflow apÃ³s build bem-sucedido da branch `${{ github.ref_name }}`.
          draft: false
          push-to-fork: false
          commit-message: '[create-pull-request] automated change'
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: mandico <43236302+mandico@users.noreply.github.com>
          signoff: false
          delete-branch: false

